# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# create author
tolkien = Author.where(name: 'J.R.R. Tolkien').first_or_create!(nationality: 'English', dob: '1892-01-03', awards: 'Great Award', biography: 'Early Life John Ronald Reuel Tolkien was born on January 3, 1892, in Bloemfontein, South Africa, to English parents. At the age of three his mother brought him ...', image_url: 'http://upload.wikimedia.org/wikipedia/commons/b/b4/Tolkien_1916.jpg')
seuss = Author.where(name: 'Dr. Seuss').first_or_create!(nationality: 'American', dob: '1904-02-03', awards: 'Caldecott Medal, Peabody Award, Pulitzer', biography: 'Theodor Seuss Geisel was born in Springfield, Massachusetts, to Theodor Robert and Henrietta (Seuss) Geisel.[4][5] All of his grandparents were German immigrants.[6] His father managed the family brewery and was later appointed to supervise Springfield public park system by Mayor John A. Denison[7] after the brewery closed because of Prohibition.[8] Mulberry Street in Springfield, made famous in Dr. Seuss first children book And to Think That I Saw It on Mulberry Street!, is less than a mile southwest of his boyhood home on Fairfield Street. Geisel was raised a Lutheran.[9] Geisel enrolled at Springfield Central High School in 1917 and graduated in 1921. He took an art class as a freshman and later became manager of the school soccer team.', image_url: 'http://ecx.images-amazon.com/images/I/51Rmbpdgh3L._UX250_.gif')


Book.where(title: 'The Hobbit').first_or_create!(isbn: '978-0547928227', author: tolkien, genre:'Fantasy', abstract: 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.', pages: 300, image_cover_url: 'http://ecx.images-amazon.com/images/I/41aQPTCmeVL.jpg', total_in_library: 5, published_on: '20120918')

Book.where(title: 'The Fellowhip of the Ring').first_or_create!(isbn: '978-0547928210', author: tolkien, genre:'Fantasy', abstract: 'In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him.', pages: 432, image_cover_url: 'http://ecx.images-amazon.com/images/I/41i-SJkyCQL.jpg', total_in_library: 5, published_on: '20120918')

Book.where(title: 'The Cat in The Hat').first_or_create!(isbn: '978-0394800011', author: seuss, genre:'Children Book', abstract:'Poor Dick and Sally. It is cold and wet and they are stuck in the house with nothing to do . . . until a giant cat in a hat shows up, transforming the dull day into a madcap adventure and almost wrecking the place in the process! Written by Dr. Seuss in 1957 in response to the concern that "pallid primers [with] abnormally courteous, unnaturally clean boys and girls were leading to growing illiteracy among children, The Cat in the Hat (the first Random House Beginner Book) changed the way our children learn how to read.', pages: 72, image_cover_url: 'http://ecx.images-amazon.com/images/I/517qxR55yML._SL500_PIsitb-sticker-arrow-big,TopRight,35,-73_OU01_SS100_.jpg', total_in_library: 5, published_on: '20040213')

Book.where(title: 'The Lorax').first_or_create!(isbn: '978-0394800011', author: seuss, genre:'Children Book', abstract:'Long before saving the earth became a global concern, Dr. Seuss, speaking through his character the Lorax, warned against mindless progress and the danger it posed to the earth is natural beauty. ' , pages: 72 , image_cover_url: 'http://ecx.images-amazon.com/images/I/51SM5e%2BY7KL._SL500_PIsitb-sticker-arrow-big,TopRight,35,-73_OU01_SS100_.jpg', total_in_library: 2, published_on: '20040213')

Book.where(title: 'Fox in Socks').first_or_create!(isbn: '978-0394800387', author: seuss, genre:'Children Book', abstract: 'This Fox is a tricky fox. He  will try to get your tongue in trouble." Dr. Seuss gives fair warning to anyone brave enough to read along with the Fox in Socks, who likes to play tongue-twisting games with his friend Mr. Knox. Here is an easy game to play. Here is an easy thing to say.... New socks. Two socks. Whose socks? Sue is socks. But Mr. Fox Socks is not about to let Knox off so easy. Soon Goo-Goose is choosing to chew chewy gluey blue goo, while tweetle beetles battle with paddles in a puddle (in case you were wondering, that is called a tweetle beetle puddle paddle battle.' , pages: 62, image_cover_url: 'http://ecx.images-amazon.com/images/I/51X3F7GQGXL._SL500_PIsitb-sticker-arrow-big,TopRight,35,-73_OU01_SS100_.jpg', total_in_library: 2, published_on: '20040213')

Book.where(title: "Oh, The Places You'll Go!").first_or_create!(isbn: '978-0679805274', author: seuss, genre:'Children Book', abstract: 'All journeys face perils, whether from indecision, from loneliness, or worst of all, from too much waiting. Seuss familiar pajama-clad hero is up to the challenge, and his odyssey is captured vividly in busy two-page spreads evoking both the good times (grinning purple elephants, floating golden castles) and the bad (deep blue wells of confusion). ' , pages: 56, image_cover_url: 'http://ecx.images-amazon.com/images/I/51LlH6e6QeL.jpg' , total_in_library: 5, published_on: '19900122')

Book.where(title: 'Green Eggs and Ham').first_or_create!(isbn: '978-0394800165', author: seuss, genre:'Children Book', abstract: "Green Eggs and Ham is a best-selling and critically acclaimed children's book by Dr. Seuss, first published on August 12, 1960. As of 2001, according to Publishers Weekly, it was the fourth best-selling English-language children's book of all time." , pages: 65, image_cover_url: 'http://ecx.images-amazon.com/images/I/71TNYAGIaIL.jpg' , total_in_library: 5, published_on: '19600812')

Book.where(title: 'How the Grinch Stole Christmas!').first_or_create!(isbn: '978-0394800790', author: seuss, genre:'Children Book', abstract: "The Grinch, whose heart is two sizes too small, hates Who-ville's holiday celebrations, and plans to steal all the presents to prevent Christmas from coming. To his amazement, Christmas comes anyway, and the Grinch discovers the true meaning of the holiday." , pages: 64, image_cover_url: 'http://ecx.images-amazon.com/images/I/512PxXsTebL.jpg' , total_in_library: 5, published_on: '19571012')

User.where(name: 'Admin').first_or_create!(password_digest: BCrypt::Password.create('password'), admin: true, password: 'password', password_confirmation: 'password')
User.where(name: 'Tim').first_or_create!(password_digest: BCrypt::Password.create('password'), admin: false, password: 'password', password_confirmation: 'password')
